/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './resources/**/*.blade.php',
    './resources/**/*.js',
    './resources/**/*.vue',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f8f9ff',
        'surface-dim': '#d1dbec',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dfe9fa',
        'surface-container-highest': '#d9e3f4',
        'on-surface': '#121c28',
        'on-surface-variant': '#424754',
        'inverse-surface': '#27313e',
        'inverse-on-surface': '#eaf1ff',
        'surface-tint': '#005ac2',
        'primary': '#0058be',
        'on-primary': '#ffffff',
        'primary-container': '#2170e4',
        'on-primary-container': '#fefcff',
        'inverse-primary': '#adc6ff',
        'secondary': '#575e70',
        'on-secondary': '#ffffff',
        'secondary-container': '#d9dff5',
        'on-secondary-container': '#5c6274',
        'tertiary': '#924700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b75b00',
        'on-tertiary-container': '#fffbff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'secondary-fixed': '#dce2f7',
        'secondary-fixed-dim': '#c0c6db',
        'on-secondary-fixed': '#141b2b',
        'on-secondary-fixed-variant': '#404758',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb786',
        'on-tertiary-fixed': '#311400',
        'on-tertiary-fixed-variant': '#723600',
        'background': '#f8f9ff',
        'on-background': '#121c28',
        'surface-variant': '#d9e3f4',
        'outline': '#727785',
        'outline-variant': '#c2c6d6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'stack-unit': '8px',
      },
      maxWidth: {
        'container-max': '1280px', // no longer referenced in Blade — we use max-w-none directly for a fluid layout instead
      },
      fontFamily: {
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'body-md': ['Inter'],
        'headline-sm': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
